version: '3.3'

services:
    nginx:

        image: nginx:latest

        container_name: nginx

        ports:
            - "80:80"
            - "443:443"

        volumes:
            - ./Nginx/core:/etc/nginx/conf.d
            - ./app:/var/www/app
            - ./Nginx/Logs:/var/log/nginx/
            - ./Nginx/html:/usr/share/nginx/html/

        links:
            - php

    mysql:

        image: mysql:5.7

        ports:
            - "3306:3306"

        container_name: somemysql

        environment:

            - MYSQL_ROOT_PASSWORD=12345
            - MYSQL_DATABASE=db
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=12345


        volumes:
            - ./MySQL:/var/lib/mysql


    php:

        build: ./PHP

        container_name: php-fpm

        volumes:
            - ./app:/var/www/app

        links:
            - mysql


    phpmyadmin:

        image: phpmyadmin/phpmyadmin

        container_name: phpmyadmin

        ports:

            - 8090:80

        links:
            - mysql:db